In [23]:
import pandas as pd
import numpy as np

In [24]:
doc=[
    'recurrent neural network',
    'artificial network',
    'connection between nodes',
    'can create a cycle',
    'allowing output',
    'som nodes to affect subsequent',
    'exhibit temporal',
    'dynamic bahavior',
    'type of neural network',
    'affect subsequent'
]

In [25]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>') # suppose we are traning our model in a corpus and in future while test we get data out of
# corpus than these text consider as nothing.

In [26]:
tokenizer.fit_on_texts(doc)

In [27]:
tokenizer.word_index

{'<nothing>': 1,
 'network': 2,
 'neural': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connection': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'som': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'bahavior': 22,
 'type': 23,
 'of': 24}

In [28]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 2),
             ('network', 3),
             ('artificial', 1),
             ('connection', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('som', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('bahavior', 1),
             ('type', 1),
             ('of', 1)])

In [29]:
tokenizer.document_count

10

In [30]:
sequence=tokenizer.texts_to_sequences(doc)

In [31]:
sequence

[[7, 3, 2],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 3, 2],
 [5, 6]]

In [32]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequence, padding='post')

In [33]:
sequences

array([[ 7,  3,  2,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  3,  2,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

## Sentiment Analysis

In [13]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [35]:
(x_train, y_train),(x_test, y_test)= imdb.load_data()

In [36]:
# y_test

In [37]:
print(len(x_train[0]))
print(len(x_train[1]))

218
189


In [38]:
# Different data point in the dataset are in different sequence. to make it in same in sequence.
x_train=pad_sequences(x_train, padding='post', maxlen=50)
x_test=pad_sequences(x_test, padding='post', maxlen=50)

In [39]:
x_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [41]:
model=Sequential()
model.add(SimpleRNN(32, input_shape=(50,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [42]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
782/782 [==============================] - 30s 36ms/step - loss: 0.6948 - accuracy: 0.5022 - val_loss: 0.6953 - val_accuracy: 0.5020
Epoch 2/5
782/782 [==============================] - 30s 38ms/step - loss: 0.6931 - accuracy: 0.5082 - val_loss: 0.6950 - val_accuracy: 0.5084
Epoch 3/5
782/782 [==============================] - 28s 36ms/step - loss: 0.6935 - accuracy: 0.5023 - val_loss: 0.6955 - val_accuracy: 0.5058
Epoch 4/5
782/782 [==============================] - 28s 35ms/step - loss: 0.6928 - accuracy: 0.5095 - val_loss: 0.6945 - val_accuracy: 0.5052
Epoch 5/5
782/782 [==============================] - 29s 37ms/step - loss: 0.6926 - accuracy: 0.5079 - val_loss: 0.6945 - val_accuracy: 0.5038


# Applying Embedding

In [1]:
doc=[
    'recurrent neural network',
    'artificial network',
    'connection between nodes',
    'can create a cycle',
    'allowing output',
    'som nodes to affect subsequent',
    'exhibit temporal',
    'dynamic bahavior',
    'type of neural network',
    'affect subsequent'
]

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')

In [3]:
tokenizer.fit_on_texts(doc)

In [4]:
tokenizer.word_index

{'<nothing>': 1,
 'network': 2,
 'neural': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connection': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'som': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'bahavior': 22,
 'type': 23,
 'of': 24}

In [5]:
len(tokenizer.word_index)

24

In [8]:
sequences=tokenizer.texts_to_sequences(doc)


In [10]:
from keras.utils import pad_sequences
sequence=pad_sequences(sequences, padding='post')

In [11]:
sequence

array([[ 7,  3,  2,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  3,  2,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

In [14]:
model=Sequential()
model.add(Embedding(24, output_dim=2, input_length=5)) # output_dim=2 means i want to represent each word in to 2 dimensions vector.
                                                      # 23 means we have 24 unique word in corpus.
                                                      # inputlength = 5 have input shape of five.


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              48        
                                                                 
Total params: 48 (192.00 Byte)
Trainable params: 48 (192.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.compile('adam','accuracy')
pred=model.predict(sequence)

1/1 [==============================] - 0s 106ms/step


In [18]:
pred

array([[[-0.0242514 ,  0.02806905],
        [ 0.04293286,  0.03998179],
        [-0.04881338,  0.04150191],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903]],

       [[-0.01052107, -0.02493796],
        [-0.04881338,  0.04150191],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903]],

       [[-0.03159342, -0.04650583],
        [-0.02235566,  0.04177484],
        [-0.03033643, -0.02898418],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903]],

       [[ 0.0230469 , -0.03418887],
        [-0.03858172,  0.04444901],
        [ 0.01908321,  0.00888281],
        [ 0.01991338,  0.000692  ],
        [-0.02702349, -0.00800903]],

       [[-0.00874726,  0.03634031],
        [-0.02009295, -0.02127758],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903],
        [-0.02702349, -0.00800903]],

       [[-0.01868496, -0.02098305],
        [-0.03033643, -0.02898418],
        [ 0.020764

## Imdb using Embedding

In [19]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [20]:
(x_train, y_train),(x_test, y_test)=imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [21]:
x_train=pad_sequences(x_train, padding='post', maxlen=50)
x_test=pad_sequences(x_test, padding='post', maxlen=50)

In [22]:
x_train.shape

(25000, 50)

In [24]:
model=Sequential()
model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,input_shape=(50,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
histoty=model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
782/782 [==============================] - 61s 74ms/step - loss: 0.5650 - acc: 0.6833 - val_loss: 0.4719 - val_acc: 0.7884
Epoch 2/5
782/782 [==============================] - 39s 50ms/step - loss: 0.3757 - acc: 0.8381 - val_loss: 0.4108 - val_acc: 0.8165
Epoch 3/5
782/782 [==============================] - 39s 50ms/step - loss: 0.3150 - acc: 0.8730 - val_loss: 0.4412 - val_acc: 0.8033
Epoch 4/5
782/782 [==============================] - 38s 49ms/step - loss: 0.2758 - acc: 0.8924 - val_loss: 0.4446 - val_acc: 0.8033
Epoch 5/5
782/782 [==============================] - 39s 49ms/step - loss: 0.2478 - acc: 0.9045 - val_loss: 0.4941 - val_acc: 0.7970


## Predication

In [29]:
x_test[0][0:50].reshape(1,-1).shape

(1, 50)

In [34]:
test_data=x_test[0][0:50].reshape(1,-1)

In [35]:
test_data

array([[  394,   354,     4,   123,     9,  1035,  1035,  1035,    10,
           10,    13,    92,   124,    89,   488,  7944,   100,    28,
         1668,    14,    31,    23,    27,  7479,    29,   220,   468,
            8,   124,    14,   286,   170,     8,   157,    46,     5,
           27,   239,    16,   179, 15387,    38,    32,    25,  7944,
          451,   202,    14,     6,   717]], dtype=int32)

In [36]:
model.predict(test_data)

1/1 [==============================] - 0s 140ms/step


array([[0.22202422]], dtype=float32)