In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [13]:
import numpy as np
import pandas as pd


In [20]:
data=pd.read_csv("/content/IMDB_Dataset.csv")

In [22]:
data=data.iloc[0:100]

In [23]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [24]:
data.shape

(100, 2)

In [25]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [26]:
data['sentiment'].value_counts()

negative    58
positive    42
Name: sentiment, dtype: int64

In [27]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [28]:
data.duplicated().sum()

0

In [29]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [30]:
data['review']=data['review'].apply(remove_html_tags)

In [31]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [32]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
exclude=string.punctuation
def remove_pun(text):
  for char in text:
    if char in exclude:
      text=text.replace(char,'')
  return text

In [34]:
text="Hello ?!+"
remove_pun(text)

'Hello '

In [35]:
data['review']=data['review'].apply(remove_url)

In [36]:
data['review']=data['review'].apply(remove_pun)

In [38]:
data['review']

0     One of the other reviewers has mentioned that ...
1     A wonderful little production The filming tech...
2     I thought this was a wonderful way to spend ti...
3     Basically theres a family where a little boy J...
4     Petter Matteis Love in the Time of Money is a ...
                            ...                        
95    Daniel DayLewis is the most versatile actor al...
96    My guess would be this was originally going to...
97    Well I like to watch bad horror BMovies cause ...
98    This IS the worst movie I have ever seen as we...
99    I have been a Mario fan for as long as I can r...
Name: review, Length: 100, dtype: object

In [39]:
#Stop words
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [42]:
# stopwords.words('english')

In [50]:
def remove_stopwords(text):
  new_text=[]
  for txt in text.split():
    if txt in stopwords.words('english'):
      new_text.append(' ')
    else:
      new_text.append(txt)
  return ' '.join(new_text)

In [51]:
data['review']=data['review'].apply(remove_stopwords)

In [52]:
data['review'][0]

'one reviewers mentioned watching 1 oz episode youll hooked   right exactly happened methe first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid   show pulls punches regards drugs sex violence   hardcore classic use wordit called oz nickname given oswald maximum security state penitentary   focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far awayi would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around   first episode   ever saw struck nasty surreal   couldnt say   ready   watched   developed taste oz got accustomed high levels graphic violence   violence injustice crooked guards wholl sold nickel inmates wholl kill order get away

In [53]:
data['review']=data['review'].str.lower()

In [49]:
data['review'][0]

'one    reviewers  mentioned   watching  1 oz episode youll  hooked they  right    exactly  happened  methe first thing  struck   oz   brutality  unflinching scenes  violence  set  right   word go trust      show   faint hearted  timid this show pulls  punches  regards  drugs sex  violence its  hardcore   classic use   wordit  called oz     nickname given   oswald maximum security state penitentary it focuses mainly  emerald city  experimental section   prison    cells  glass fronts  face inwards  privacy   high   agenda em city  home  manyaryans muslims gangstas latinos christians italians irish  moreso scuffles death stares dodgy dealings  shady agreements  never far awayi would say  main appeal   show  due   fact   goes   shows wouldnt dare forget pretty pictures painted  mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck    nasty   surreal i couldnt say i  ready     i watched  i developed  taste  oz  got accustomed   high level

In [54]:
# Stemmer
from nltk.stem.porter import PorterStemmer

In [60]:
ps=PorterStemmer()
def stem_words(text):
  new_word=[]
  for word in text.split():
    new_word.append(ps.stem(word))
  return " ".join(new_word)

In [63]:
data['review']=data['review'].apply(stem_words)

In [64]:
data['review'][0]

'one review mention watch 1 oz episod youll hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show wouldnt dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz doesnt mess around first episod ever saw struck nasti surreal couldnt say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard wholl sold nickel inmat wholl kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom c

In [66]:
x=data.iloc[:,[0]]
y=data.iloc[:,[1]]

In [68]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
y=encode.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [69]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [71]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [72]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((80, 1), (20, 1), (80,), (20,))

In [77]:
## Applying Bow
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [88]:
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()

In [79]:
x_train_bow.shape, x_test_bow.shape

((80, 3255), (20, 3255))

In [81]:
x_train_bow[0]

array([0, 0, 0, ..., 0, 1, 0])

In [84]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

gnb.fit(x_train_bow, y_train)

GaussianNB()

In [85]:
y_pred=gnb.predict(x_test_bow)
from sklearn.metrics import accuracy_score, confusion_matrix


In [86]:
accuracy_score(y_test, y_pred)

0.6

In [87]:
confusion_matrix(y_test, y_pred)

array([[5, 1],
       [7, 7]])

In [91]:
from sklearn.ensemble import RandomForestClassifier

In [92]:
cv=CountVectorizer(max_features=3000)
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()


rf=RandomForestClassifier()

rf.fit(x_train_bow, y_train)
y_pred=rf.predict(x_test_bow)

accuracy_score(y_test, y_pred)

0.35